42-8

diff --git a/.github/workflows/publish-multiple-libs.yml b/.github/workflows/publish-multiple-libs.yml
--- a/.github/workflows/publish-multiple-libs.yml
+++ b/.github/workflows/publish-multiple-libs.yml
@@ -37,17 +37,36 @@ jobs:
           package: ./packages/npm-auto-publish-test-mono-repo-2
       - name: Set output vars
         run: |
-          echo "::set-output name=mono_A::{!!steps.publish_mono.outputs.value}"
-          echo "::set-output name=mono_B::{!!steps.publish_mono_type.outputs.value}"
+          echo "MONO_A={{ !!steps.publish_mono.outputs.value }}" >> "$GITHUB_OUTPUT"
+          echo "MONO_B={{ !!steps.publish_mono_type.outputs.value }}" >> "$GITHUB_OUTPUT"
   check-mono:
     name: Test A
     runs-on: ubuntu-latest
     needs: [ publish ]
     steps:
-      - run: echo ${{ needs.publish.outputs.mono_A }}
+      - name: publico
+        run: |
+          echo "${{ needs.publish.outputs.MONO_A }}"
+          if [[ !needs.publish.outputs.MONO_A ]]; then
+            echo "Publication Error: Both packages failed to publish. Did you changed package.json version? Please review and try again."
+            exit 1
+          else
+            echo "Version A published"
+            exit 0
+          fi
+
   check-mono-b:
     name: Test b
     runs-on: ubuntu-latest
     needs: [ publish ]
     steps:
-      - run: echo ${{ needs.publish.outputs.mono_B }}
+      - name: publico
+        run: |
+          echo "${{ needs.publish.outputs.MONO_B }}"
+          if [[ !needs.publish.outputs.MONO_B ]]; then
+            echo "Publication Error: Both packages failed to publish. Did you changed package.json version? Please review and try again."
+            exit 1
+          else
+            echo "Version A published"
+            exit 0
+          fi
